# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Energy',
        ),
    ]
