# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0002_delete_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('energy', models.CharField(max_length=255)),
            ],
        ),
    ]
