# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='energy',
            name='energy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='energy',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
