# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_auto_20170703_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateandTime', models.DateTimeField()),
                ('energy', models.FloatField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Energy',
        ),
    ]
